# default configuration
baseURL = "http://examplesite.com"
languageCode = "en-us"
summaryLength = "10"
theme = "Kross"
title = "Hugo Loiseau"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "À propos"
weight = 1

[[menu.main]]
URL = "skills"
name = "Compétences"
weight = 2

[[menu.main]]
URL = "projects"
name = "Réalisations"
weight = 3

[[menu.main]]
URL = "https://drive.google.com/file/d/194ucgFgg9jjYQaTzf-l5Sxk_iznQTPaA/view?usp=sharing"
name = "CV"
weight = 4


# default parameters
[params]
home = "Accueil"
logo = ""
# theme color
theme_color = "#248aaa"
# contact info
phone = "+880 2544 658 256"
email = "steve.fruits@email.com"
address = "125/A, CA Commercial Area, California, USA"
# meta description
author = "Hugo Loiseau"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2021 Hugo Loiseau"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# social site
[[params.social]]
icon = "ti-github"
URL = "#"

[[params.social]]
icon = "ti-linkedin"
URL = "#"